### ISSUE TITLE
After installation i can not see "Enable Security Policy in WHM » Home » Security Center » Configure Security Policies" but here is one check box which is "blank"

### ISSUE THREAD

**Issue by mehulsbhatt** [steadramon/cpanel_addon-twostepauth#3]
Hello,

Recently i have install twostepauth on my cPanel/WHM version 11.46.1 

After installation i can not see "Enable Security Policy in WHM » Home » Security Center » Configure Security Policies" but here is one check box which is "blank"

Please advice how can i resolve this issue.

Thanks.

**Comment by dhawton** [comment]
I have the same issue.

**Comment by steadramon** [comment]
Commit e6eb1e00d62214e8db15588342cf2271224b33a2 should fix
