### ISSUE TITLE
Can't active for users

### ISSUE THREAD

**Issue by dhawton** [steadramon/cpanel_addon-twostepauth#4]
In WHM > Plugins > cPanel TSA I go to Users and try to activate it, but the column stays "Inactive" and the icon does not appear in the user panel for any of the users.  I enabled it under security policies and the plugin config.

Further playing found it's not creating the config file for the user.  When I activate and ls -a ~user, no .twostepauth is found.  When I create the directory and file conf with text enabled=1, it appears to show as activated but is not showing up on x3 or paper lantern cPanel for said user.

**Comment by dhawton** [comment]
Further playing found it's not creating the config file for the user.  When I activate and ls -a ~user, no .twostepauth is found.  When I create the directory and file conf with text enabled=1, it appears to show as activated but is not showing up on x3 or paper lantern cPanel for said user.

**Comment by dhawton** [comment]
Works if you manually add /twostepauth/ to the URL after /x3/ and before index.html.  You can configure it and it fully works.  It's just not adding the icon to the X3 theme.

Is it possible to use with WHM or is this for cPanel only?

**Comment by steadramon** [comment]
I'll look at the enabling/disabling for the users in WHM.

Regarding the Icon availability in cPanel - is Two Step Auth enabled in the feature list for the account in question?

Currently this is just for cPanel logins only.

**Comment by steadramon** [comment]
Actually, it may be a bad idea to be able to enable TSA through WHM for a cPanel account, as the user will not have had chance to scan the QR code.

**Comment by dhawton** [comment]
I was seeing if it would be possible, since the code was there to allow it (or at least appeared that way).  Two Step Auth is enabled in Feature Manager for the list used by the users and the icon still does not display.

**Comment by steadramon** [comment]
Commit ab4a14cd15d7a320d173fea3eaa0daef24f185c5 uses cpanelfeature to ensure the account in question has access to the feature - if you access the page directly after this update do you still see the settings manager?

**Comment by dhawton** [comment]
Still not listed under Security, no errors on install, and when visiting the URL manually it does still display the settings manager.

**Comment by toxicwombat** [comment]
I was running into the same problem.  It doesn't appear that the entry was being added to /usr/local/cpanel/base/frontend/x3/dynamicui.conf .  I manually added the entry, then ran /usr/local/cpanel/bin/rebuild_sprites afterward and the entry and icon are now appearing.

**Comment by steadramon** [comment]
The file on my version is put in /usr/local/cpanel/base/frontend/x3/dynamicui/dynamicui_twostepauth.conf for x3 - what version of cPanel are you using?

**Comment by toxicwombat** [comment]
Using WHM 11.46.2

**Comment by dhawton** [comment]
As of tonight with the latest release of cPanel, the plugin is working.  Thank you!

**Comment by steadramon** [comment]
Excellent, many thanks

**Comment by dheerajpundir** [comment]
Hi there i installed the plugin and activate but once i scan the qr and activate the plugin from cpanel and then logout and login again the cpanel ask for code when i enter the authorization code its get back with erro
![cpanel_addon-twostepauth](https://cloud.githubusercontent.com/assets/6213442/7103564/866f993e-e0ca-11e4-8adf-9c47bbf687db.png)

Please help me to get resolve

**Comment by dheerajpundir** [comment]
Its work find with Authy: Two-Factor Authentication
