### ISSUE TITLE
Invalid Barcode

### ISSUE THREAD

**Issue by SkinnyBill** [steadramon/cpanel_addon-twostepauth#5]
Just installed on my WHM server. When i try to add the QR to my phone, Google Authenticator says this is an invalid barcode:

"The barcode: [xxx] is not a valid authentication token barcode."

From a little googling, it appears this happens on iPhones if there is a space in the barcode. Could you please check this?

**Comment by steadramon** [comment]
Latest comit should fix

**Comment by SkinnyBill** [comment]
This didn't fix the problem. I see it now inserts "%20" instead of the space, but apparently the iPhone version of Google Authenticator still doesn't like this.

According to this page:
http://www.wpbeginner.com/plugins/improve-wordpress-security-with-google-authenticator/
"Note: When using iPhone, you can’t spaces in your description. Because in the above screenshot we have a space in our description “WPBeginner Blog”, we will have to use the key to enter the information in our application manually. The QR code will not work. If you want to just scan the QR code, then you have to make your description without spaces like this “WPBeginnerBlog”."

In this case, could you either make it so that there is a text field to add your own description to the QR, or just force names to not use spaces (eg. cPanelUsername or cPanel_username or something).

**Comment by SkinnyBill** [comment]
Can I confirm you have still seen the above message? This could do with being re-opened :)

**Comment by steadramon** [comment]
Hmm interesting one - I wonder where the issue comes in - regretably I'll update to have underscore or similar instead of a space - the urlcoded version should really work though... Silly iPhones

**Comment by steadramon** [comment]
OK got a hold of an iPhone to test this - I don't think it's the space causing the issue... investigating

**Comment by steadramon** [comment]
OK - want to test this for me now on the latest commit?

**Comment by SkinnyBill** [comment]
Sure I can test it out, give me an hour or two just to get back :)

**Comment by SkinnyBill** [comment]
Ok, this definitely works now. My only minor suggestion would be to still put the username in the description somewhere, just in case someone has 2 accounts on the same server.

Also, just a tiny note, when typing in the code to log in, it doesn't accept a space in the code (eg. "123 456" as shown in Authenticator will be invalid, but 123456 will work). Just ignore the space :)

**Comment by steadramon** [comment]
Great - is the username still not included in your title string?

I'll look at replacing out spaces

**Comment by SkinnyBill** [comment]
No, my apologies. I didn't notice that it appears in the second string as "cPanel Username". It just looks like it's the URL it doesn't like spaces in.

**Comment by steadramon** [comment]
Thanks for your help and feedback. Closing. Have raised #8 for suggestion
